#!/bin/bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$#" -lt 2 ]; then
  echo "usage: cub <input-file> <output-file>" >&2
  exit 1
fi

mkdir -p "$DIR/out/lib/"
gcc -S "$DIR/llvm-backend/llvm-harness.c" -o "$DIR/out/lib/llvm-harness.s"
"$DIR/out/Debug/cub" "$1" | llc | gcc -lm -xassembler - "$DIR/out/lib/llvm-harness.s" -o "$2"
